import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Recording from '../components/index';

export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
         <link href="http://netdna.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" /> 
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        የአማርኛ ጽሑፍ ወደ ንግግር መረጃ መሰብሰብያ
        </h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Recording />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            G3
          </span>
        </a>
      </footer>
      <style jsx>{`
        .record-button {
          height: 8em;
          width: 8em;
          border-color: #f3f3f3 !important;
        }
        
        .record-button:hover {
          box-shadow: 0 .5rem 1rem rgba(0,0,0,.15)!important;
        }
        .play-button:hover {
          box-shadow: 0 .5rem 1rem rgba(0,0,0,.15)!important;
        }
        
        .play-button {
          height: 8em;
          width: 8em;
          background-color: #5084d2;
        }
      
      `}</style>

    </div>
  )
}
